### ISSUE TITLE
Problem running "evaluations_blogcatalog.sh"

### ISSUE THREAD

**Issue by yumiao2** [uqhwen2/GraphDKL#1]
RuntimeError: Error(s) in loading state_dict for GraphDKL:
        Missing key(s) in state_dict: "gnn.sage1.lin_l.weight_u", "gnn.sage1.lin_l.weight_v", "gnn.sage1.lin_r.weight_u", "gnn.sage1.lin_r.weight_v", "gnn.sage2.lin_l.weight_u", "gnn.sage2.lin_l.weight_v", "gnn.sage2.lin_r.weight_u", "gnn.sage2.lin_r.weight_v".

**Comment by uqhwen2** [comment]
Hi there, 

Do you download the latest version of the repo? I can run it properly without this issue. Can I confirm that can you properly train the model? 

This issue occurs due to the spectral norm module should not be initialised as part of the model instance when reloading from the saved .dat trained model. Thus, in the defined `GraphSAGE` extractor from `models/graphdkl.py`, I especially set in the evaluation ('eval') stage, the SAGE convolution is initialised without the spectral normalisation.

`class GraphSAGE(nn.Module):

    def __init__(self, dim_in, dim_h, status, stage):
        super().__init__()
        
        if stage == 'train':
            if status == 'WithSN':
                self.sage1 = SN_SAGEConv(dim_in, dim_h, aggr='max', normalize=True)
                self.sage2 = SN_SAGEConv(dim_h, dim_h, aggr='max', normalize=True) 
            else:
                self.sage1 = SAGEConv(dim_in, dim_h, aggr='max', normalize=True)
                self.sage2 = SAGEConv(dim_h, dim_h, aggr='max', normalize=True) 
                
        elif stage == 'eval':
                self.sage1 = SAGEConv(dim_in, dim_h, aggr='max', normalize=True)
                self.sage2 = SAGEConv(dim_h, dim_h, aggr='max', normalize=True)  
            
    def forward(self, x, edge_index):
        h = F.relu(self.sage1(x, edge_index))
        h = F.dropout(h, 0.1, training=self.training)
        h = F.relu(self.sage2(h, edge_index))
        h = F.dropout(h, 0.1, training=self.training)

        return h`



Also, can you trained a model without spectral normalisation? Just set the `--mode WithSN` to `--mode WithOSN` (The O is not Zero, just uppercase O) in the `main_blogcatalog.sh`, and do the same to `evaluations_blogcatalog.sh`, can you run the code without the spectral normalisation properly? If so, then if same issue still encounter for `--mode WithSN`, please check if the `class GraphSAGE` is the same as provided here or reply back to this thread.

**Comment by yumiao2** [comment]
Thank you very much for your answer. When I ran evaluations_blogcatalog.sh, I replaced "SN_SAGEConv" in the GraphSAGE function with "SAGEConv" and got the result smoothly.

**Comment by uqhwen2** [comment]
Good to hear that, strictly follow the instruction in the `README.md` file should guarantee a smooth run of the code as I've tested it many times on different Linux platforms from scratch.
